#ifndef __DEBUG_RPINT_H__
#define __DEBUG_RPINT_H__


inline const wchar_t* SdlScanCodeString(SDL_Scancode scan)
{
	switch (scan)
	{
		//case SDL_SCANCODE_UNKNOWN            : return L"SDL_SCANCODE_UNKNOWN";
	case SDL_SCANCODE_A: return L"SDL_SCANCODE_A";
	case SDL_SCANCODE_B: return L"SDL_SCANCODE_B";
	case SDL_SCANCODE_C: return L"SDL_SCANCODE_C";
	case SDL_SCANCODE_D: return L"SDL_SCANCODE_D";
	case SDL_SCANCODE_E: return L"SDL_SCANCODE_E";
	case SDL_SCANCODE_F: return L"SDL_SCANCODE_F";
	case SDL_SCANCODE_G: return L"SDL_SCANCODE_G";
	case SDL_SCANCODE_H: return L"SDL_SCANCODE_H";
	case SDL_SCANCODE_I: return L"SDL_SCANCODE_I";
	case SDL_SCANCODE_J: return L"SDL_SCANCODE_J";
	case SDL_SCANCODE_K: return L"SDL_SCANCODE_K";
	case SDL_SCANCODE_L: return L"SDL_SCANCODE_L";
	case SDL_SCANCODE_M: return L"SDL_SCANCODE_M";
	case SDL_SCANCODE_N: return L"SDL_SCANCODE_N";
	case SDL_SCANCODE_O: return L"SDL_SCANCODE_O";
	case SDL_SCANCODE_P: return L"SDL_SCANCODE_P";
	case SDL_SCANCODE_Q: return L"SDL_SCANCODE_Q";
	case SDL_SCANCODE_R: return L"SDL_SCANCODE_R";
	case SDL_SCANCODE_S: return L"SDL_SCANCODE_S";
	case SDL_SCANCODE_T: return L"SDL_SCANCODE_T";
	case SDL_SCANCODE_U: return L"SDL_SCANCODE_U";
	case SDL_SCANCODE_V: return L"SDL_SCANCODE_V";
	case SDL_SCANCODE_W: return L"SDL_SCANCODE_W";
	case SDL_SCANCODE_X: return L"SDL_SCANCODE_X";
	case SDL_SCANCODE_Y: return L"SDL_SCANCODE_Y";
	case SDL_SCANCODE_Z: return L"SDL_SCANCODE_Z";
	case SDL_SCANCODE_1: return L"SDL_SCANCODE_1";
	case SDL_SCANCODE_2: return L"SDL_SCANCODE_2";
	case SDL_SCANCODE_3: return L"SDL_SCANCODE_3";
	case SDL_SCANCODE_4: return L"SDL_SCANCODE_4";
	case SDL_SCANCODE_5: return L"SDL_SCANCODE_5";
	case SDL_SCANCODE_6: return L"SDL_SCANCODE_6";
	case SDL_SCANCODE_7: return L"SDL_SCANCODE_7";
	case SDL_SCANCODE_8: return L"SDL_SCANCODE_8";
	case SDL_SCANCODE_9: return L"SDL_SCANCODE_9";
	case SDL_SCANCODE_0: return L"SDL_SCANCODE_0";
	case SDL_SCANCODE_RETURN: return L"SDL_SCANCODE_RETURN";
	case SDL_SCANCODE_ESCAPE: return L"SDL_SCANCODE_ESCAPE";
	case SDL_SCANCODE_BACKSPACE: return L"SDL_SCANCODE_BACKSPACE";
	case SDL_SCANCODE_TAB: return L"SDL_SCANCODE_TAB";
	case SDL_SCANCODE_SPACE: return L"SDL_SCANCODE_SPACE";
	case SDL_SCANCODE_MINUS: return L"SDL_SCANCODE_MINUS";
	case SDL_SCANCODE_EQUALS: return L"SDL_SCANCODE_EQUALS";
	case SDL_SCANCODE_LEFTBRACKET: return L"SDL_SCANCODE_LEFTBRACKET";
	case SDL_SCANCODE_RIGHTBRACKET: return L"SDL_SCANCODE_RIGHTBRACKET";
	case SDL_SCANCODE_BACKSLASH: return L"SDL_SCANCODE_BACKSLASH";
	case SDL_SCANCODE_NONUSHASH: return L"SDL_SCANCODE_NONUSHASH";
	case SDL_SCANCODE_SEMICOLON: return L"SDL_SCANCODE_SEMICOLON";
	case SDL_SCANCODE_APOSTROPHE: return L"SDL_SCANCODE_APOSTROPHE";
	case SDL_SCANCODE_GRAVE: return L"SDL_SCANCODE_GRAVE";
	case SDL_SCANCODE_COMMA: return L"SDL_SCANCODE_COMMA";
	case SDL_SCANCODE_PERIOD: return L"SDL_SCANCODE_PERIOD";
	case SDL_SCANCODE_SLASH: return L"SDL_SCANCODE_SLASH";
	case SDL_SCANCODE_CAPSLOCK: return L"SDL_SCANCODE_CAPSLOCK";
	case SDL_SCANCODE_F1: return L"SDL_SCANCODE_F1";
	case SDL_SCANCODE_F2: return L"SDL_SCANCODE_F2";
	case SDL_SCANCODE_F3: return L"SDL_SCANCODE_F3";
	case SDL_SCANCODE_F4: return L"SDL_SCANCODE_F4";
	case SDL_SCANCODE_F5: return L"SDL_SCANCODE_F5";
	case SDL_SCANCODE_F6: return L"SDL_SCANCODE_F6";
	case SDL_SCANCODE_F7: return L"SDL_SCANCODE_F7";
	case SDL_SCANCODE_F8: return L"SDL_SCANCODE_F8";
	case SDL_SCANCODE_F9: return L"SDL_SCANCODE_F9";
	case SDL_SCANCODE_F10: return L"SDL_SCANCODE_F10";
	case SDL_SCANCODE_F11: return L"SDL_SCANCODE_F11";
	case SDL_SCANCODE_F12: return L"SDL_SCANCODE_F12";
	case SDL_SCANCODE_PRINTSCREEN: return L"SDL_SCANCODE_PRINTSCREEN";
	case SDL_SCANCODE_SCROLLLOCK: return L"SDL_SCANCODE_SCROLLLOCK";
	case SDL_SCANCODE_PAUSE: return L"SDL_SCANCODE_PAUSE";
	case SDL_SCANCODE_INSERT: return L"SDL_SCANCODE_INSERT";
	case SDL_SCANCODE_HOME: return L"SDL_SCANCODE_HOME";
	case SDL_SCANCODE_PAGEUP: return L"SDL_SCANCODE_PAGEUP";
	case SDL_SCANCODE_DELETE: return L"SDL_SCANCODE_DELETE";
	case SDL_SCANCODE_END: return L"SDL_SCANCODE_END";
	case SDL_SCANCODE_PAGEDOWN: return L"SDL_SCANCODE_PAGEDOWN";
	case SDL_SCANCODE_RIGHT: return L"SDL_SCANCODE_RIGHT";
	case SDL_SCANCODE_LEFT: return L"SDL_SCANCODE_LEFT";
	case SDL_SCANCODE_DOWN: return L"SDL_SCANCODE_DOWN";
	case SDL_SCANCODE_UP: return L"SDL_SCANCODE_UP";
	case SDL_SCANCODE_NUMLOCKCLEAR: return L"SDL_SCANCODE_NUMLOCKCLEAR";
	case SDL_SCANCODE_KP_DIVIDE: return L"SDL_SCANCODE_KP_DIVIDE";
	case SDL_SCANCODE_KP_MULTIPLY: return L"SDL_SCANCODE_KP_MULTIPLY";
	case SDL_SCANCODE_KP_MINUS: return L"SDL_SCANCODE_KP_MINUS";
	case SDL_SCANCODE_KP_PLUS: return L"SDL_SCANCODE_KP_PLUS";
	case SDL_SCANCODE_KP_ENTER: return L"SDL_SCANCODE_KP_ENTER";
	case SDL_SCANCODE_KP_1: return L"SDL_SCANCODE_KP_1";
	case SDL_SCANCODE_KP_2: return L"SDL_SCANCODE_KP_2";
	case SDL_SCANCODE_KP_3: return L"SDL_SCANCODE_KP_3";
	case SDL_SCANCODE_KP_4: return L"SDL_SCANCODE_KP_4";
	case SDL_SCANCODE_KP_5: return L"SDL_SCANCODE_KP_5";
	case SDL_SCANCODE_KP_6: return L"SDL_SCANCODE_KP_6";
	case SDL_SCANCODE_KP_7: return L"SDL_SCANCODE_KP_7";
	case SDL_SCANCODE_KP_8: return L"SDL_SCANCODE_KP_8";
	case SDL_SCANCODE_KP_9: return L"SDL_SCANCODE_KP_9";
	case SDL_SCANCODE_KP_0: return L"SDL_SCANCODE_KP_0";
	case SDL_SCANCODE_KP_PERIOD: return L"SDL_SCANCODE_KP_PERIOD";
	case SDL_SCANCODE_NONUSBACKSLASH: return L"SDL_SCANCODE_NONUSBACKSLASH";
	case SDL_SCANCODE_APPLICATION: return L"SDL_SCANCODE_APPLICATION";
	case SDL_SCANCODE_POWER: return L"SDL_SCANCODE_POWER";
	case SDL_SCANCODE_KP_EQUALS: return L"SDL_SCANCODE_KP_EQUALS";
	case SDL_SCANCODE_F13: return L"SDL_SCANCODE_F13";
	case SDL_SCANCODE_F14: return L"SDL_SCANCODE_F14";
	case SDL_SCANCODE_F15: return L"SDL_SCANCODE_F15";
	case SDL_SCANCODE_F16: return L"SDL_SCANCODE_F16";
	case SDL_SCANCODE_F17: return L"SDL_SCANCODE_F17";
	case SDL_SCANCODE_F18: return L"SDL_SCANCODE_F18";
	case SDL_SCANCODE_F19: return L"SDL_SCANCODE_F19";
	case SDL_SCANCODE_F20: return L"SDL_SCANCODE_F20";
	case SDL_SCANCODE_F21: return L"SDL_SCANCODE_F21";
	case SDL_SCANCODE_F22: return L"SDL_SCANCODE_F22";
	case SDL_SCANCODE_F23: return L"SDL_SCANCODE_F23";
	case SDL_SCANCODE_F24: return L"SDL_SCANCODE_F24";
	case SDL_SCANCODE_EXECUTE: return L"SDL_SCANCODE_EXECUTE";
	case SDL_SCANCODE_HELP: return L"SDL_SCANCODE_HELP";
	case SDL_SCANCODE_MENU: return L"SDL_SCANCODE_MENU";
	case SDL_SCANCODE_SELECT: return L"SDL_SCANCODE_SELECT";
	case SDL_SCANCODE_STOP: return L"SDL_SCANCODE_STOP";
	case SDL_SCANCODE_AGAIN: return L"SDL_SCANCODE_AGAIN";
	case SDL_SCANCODE_UNDO: return L"SDL_SCANCODE_UNDO";
	case SDL_SCANCODE_CUT: return L"SDL_SCANCODE_CUT";
	case SDL_SCANCODE_COPY: return L"SDL_SCANCODE_COPY";
	case SDL_SCANCODE_PASTE: return L"SDL_SCANCODE_PASTE";
	case SDL_SCANCODE_FIND: return L"SDL_SCANCODE_FIND";
	case SDL_SCANCODE_MUTE: return L"SDL_SCANCODE_MUTE";
	case SDL_SCANCODE_VOLUMEUP: return L"SDL_SCANCODE_VOLUMEUP";
	case SDL_SCANCODE_VOLUMEDOWN: return L"SDL_SCANCODE_VOLUMEDOWN";
	case SDL_SCANCODE_KP_COMMA: return L"SDL_SCANCODE_KP_COMMA";
	case SDL_SCANCODE_KP_EQUALSAS400: return L"SDL_SCANCODE_KP_EQUALSAS400";
	case SDL_SCANCODE_INTERNATIONAL1: return L"SDL_SCANCODE_INTERNATIONAL1";
	case SDL_SCANCODE_INTERNATIONAL2: return L"SDL_SCANCODE_INTERNATIONAL2";
	case SDL_SCANCODE_INTERNATIONAL3: return L"SDL_SCANCODE_INTERNATIONAL3";
	case SDL_SCANCODE_INTERNATIONAL4: return L"SDL_SCANCODE_INTERNATIONAL4";
	case SDL_SCANCODE_INTERNATIONAL5: return L"SDL_SCANCODE_INTERNATIONAL5";
	case SDL_SCANCODE_INTERNATIONAL6: return L"SDL_SCANCODE_INTERNATIONAL6";
	case SDL_SCANCODE_INTERNATIONAL7: return L"SDL_SCANCODE_INTERNATIONAL7";
	case SDL_SCANCODE_INTERNATIONAL8: return L"SDL_SCANCODE_INTERNATIONAL8";
	case SDL_SCANCODE_INTERNATIONAL9: return L"SDL_SCANCODE_INTERNATIONAL9";
	case SDL_SCANCODE_LANG1: return L"SDL_SCANCODE_LANG1";
	case SDL_SCANCODE_LANG2: return L"SDL_SCANCODE_LANG2";
	case SDL_SCANCODE_LANG3: return L"SDL_SCANCODE_LANG3";
	case SDL_SCANCODE_LANG4: return L"SDL_SCANCODE_LANG4";
	case SDL_SCANCODE_LANG5: return L"SDL_SCANCODE_LANG5";
	case SDL_SCANCODE_LANG6: return L"SDL_SCANCODE_LANG6";
	case SDL_SCANCODE_LANG7: return L"SDL_SCANCODE_LANG7";
	case SDL_SCANCODE_LANG8: return L"SDL_SCANCODE_LANG8";
	case SDL_SCANCODE_LANG9: return L"SDL_SCANCODE_LANG9";
	case SDL_SCANCODE_ALTERASE: return L"SDL_SCANCODE_ALTERASE";
	case SDL_SCANCODE_SYSREQ: return L"SDL_SCANCODE_SYSREQ";
	case SDL_SCANCODE_CANCEL: return L"SDL_SCANCODE_CANCEL";
	case SDL_SCANCODE_CLEAR: return L"SDL_SCANCODE_CLEAR";
	case SDL_SCANCODE_PRIOR: return L"SDL_SCANCODE_PRIOR";
	case SDL_SCANCODE_RETURN2: return L"SDL_SCANCODE_RETURN2";
	case SDL_SCANCODE_SEPARATOR: return L"SDL_SCANCODE_SEPARATOR";
	case SDL_SCANCODE_OUT: return L"SDL_SCANCODE_OUT";
	case SDL_SCANCODE_OPER: return L"SDL_SCANCODE_OPER";
	case SDL_SCANCODE_CLEARAGAIN: return L"SDL_SCANCODE_CLEARAGAIN";
	case SDL_SCANCODE_CRSEL: return L"SDL_SCANCODE_CRSEL";
	case SDL_SCANCODE_EXSEL: return L"SDL_SCANCODE_EXSEL";
	case SDL_SCANCODE_KP_00: return L"SDL_SCANCODE_KP_00";
	case SDL_SCANCODE_KP_000: return L"SDL_SCANCODE_KP_000";
	case SDL_SCANCODE_THOUSANDSSEPARATOR: return L"SDL_SCANCODE_THOUSANDSSEPARATOR";
	case SDL_SCANCODE_DECIMALSEPARATOR: return L"SDL_SCANCODE_DECIMALSEPARATOR";
	case SDL_SCANCODE_CURRENCYUNIT: return L"SDL_SCANCODE_CURRENCYUNIT";
	case SDL_SCANCODE_CURRENCYSUBUNIT: return L"SDL_SCANCODE_CURRENCYSUBUNIT";
	case SDL_SCANCODE_KP_LEFTPAREN: return L"SDL_SCANCODE_KP_LEFTPAREN";
	case SDL_SCANCODE_KP_RIGHTPAREN: return L"SDL_SCANCODE_KP_RIGHTPAREN";
	case SDL_SCANCODE_KP_LEFTBRACE: return L"SDL_SCANCODE_KP_LEFTBRACE";
	case SDL_SCANCODE_KP_RIGHTBRACE: return L"SDL_SCANCODE_KP_RIGHTBRACE";
	case SDL_SCANCODE_KP_TAB: return L"SDL_SCANCODE_KP_TAB";
	case SDL_SCANCODE_KP_BACKSPACE: return L"SDL_SCANCODE_KP_BACKSPACE";
	case SDL_SCANCODE_KP_A: return L"SDL_SCANCODE_KP_A";
	case SDL_SCANCODE_KP_B: return L"SDL_SCANCODE_KP_B";
	case SDL_SCANCODE_KP_C: return L"SDL_SCANCODE_KP_C";
	case SDL_SCANCODE_KP_D: return L"SDL_SCANCODE_KP_D";
	case SDL_SCANCODE_KP_E: return L"SDL_SCANCODE_KP_E";
	case SDL_SCANCODE_KP_F: return L"SDL_SCANCODE_KP_F";
	case SDL_SCANCODE_KP_XOR: return L"SDL_SCANCODE_KP_XOR";
	case SDL_SCANCODE_KP_POWER: return L"SDL_SCANCODE_KP_POWER";
	case SDL_SCANCODE_KP_PERCENT: return L"SDL_SCANCODE_KP_PERCENT";
	case SDL_SCANCODE_KP_LESS: return L"SDL_SCANCODE_KP_LESS";
	case SDL_SCANCODE_KP_GREATER: return L"SDL_SCANCODE_KP_GREATER";
	case SDL_SCANCODE_KP_AMPERSAND: return L"SDL_SCANCODE_KP_AMPERSAND";
	case SDL_SCANCODE_KP_DBLAMPERSAND: return L"SDL_SCANCODE_KP_DBLAMPERSAND";
	case SDL_SCANCODE_KP_VERTICALBAR: return L"SDL_SCANCODE_KP_VERTICALBAR";
	case SDL_SCANCODE_KP_DBLVERTICALBAR: return L"SDL_SCANCODE_KP_DBLVERTICALBAR";
	case SDL_SCANCODE_KP_COLON: return L"SDL_SCANCODE_KP_COLON";
	case SDL_SCANCODE_KP_HASH: return L"SDL_SCANCODE_KP_HASH";
	case SDL_SCANCODE_KP_SPACE: return L"SDL_SCANCODE_KP_SPACE";
	case SDL_SCANCODE_KP_AT: return L"SDL_SCANCODE_KP_AT";
	case SDL_SCANCODE_KP_EXCLAM: return L"SDL_SCANCODE_KP_EXCLAM";
	case SDL_SCANCODE_KP_MEMSTORE: return L"SDL_SCANCODE_KP_MEMSTORE";
	case SDL_SCANCODE_KP_MEMRECALL: return L"SDL_SCANCODE_KP_MEMRECALL";
	case SDL_SCANCODE_KP_MEMCLEAR: return L"SDL_SCANCODE_KP_MEMCLEAR";
	case SDL_SCANCODE_KP_MEMADD: return L"SDL_SCANCODE_KP_MEMADD";
	case SDL_SCANCODE_KP_MEMSUBTRACT: return L"SDL_SCANCODE_KP_MEMSUBTRACT";
	case SDL_SCANCODE_KP_MEMMULTIPLY: return L"SDL_SCANCODE_KP_MEMMULTIPLY";
	case SDL_SCANCODE_KP_MEMDIVIDE: return L"SDL_SCANCODE_KP_MEMDIVIDE";
	case SDL_SCANCODE_KP_PLUSMINUS: return L"SDL_SCANCODE_KP_PLUSMINUS";
	case SDL_SCANCODE_KP_CLEAR: return L"SDL_SCANCODE_KP_CLEAR";
	case SDL_SCANCODE_KP_CLEARENTRY: return L"SDL_SCANCODE_KP_CLEARENTRY";
	case SDL_SCANCODE_KP_BINARY: return L"SDL_SCANCODE_KP_BINARY";
	case SDL_SCANCODE_KP_OCTAL: return L"SDL_SCANCODE_KP_OCTAL";
	case SDL_SCANCODE_KP_DECIMAL: return L"SDL_SCANCODE_KP_DECIMAL";
	case SDL_SCANCODE_KP_HEXADECIMAL: return L"SDL_SCANCODE_KP_HEXADECIMAL";
	case SDL_SCANCODE_LCTRL: return L"SDL_SCANCODE_LCTRL";
	case SDL_SCANCODE_LSHIFT: return L"SDL_SCANCODE_LSHIFT";
	case SDL_SCANCODE_LALT: return L"SDL_SCANCODE_LALT";
	case SDL_SCANCODE_LGUI: return L"SDL_SCANCODE_LGUI";
	case SDL_SCANCODE_RCTRL: return L"SDL_SCANCODE_RCTRL";
	case SDL_SCANCODE_RSHIFT: return L"SDL_SCANCODE_RSHIFT";
	case SDL_SCANCODE_RALT: return L"SDL_SCANCODE_RALT";
	case SDL_SCANCODE_RGUI: return L"SDL_SCANCODE_RGUI";
	case SDL_SCANCODE_MODE: return L"SDL_SCANCODE_MODE";
	case SDL_SCANCODE_AUDIONEXT: return L"SDL_SCANCODE_AUDIONEXT";
	case SDL_SCANCODE_AUDIOPREV: return L"SDL_SCANCODE_AUDIOPREV";
	case SDL_SCANCODE_AUDIOSTOP: return L"SDL_SCANCODE_AUDIOSTOP";
	case SDL_SCANCODE_AUDIOPLAY: return L"SDL_SCANCODE_AUDIOPLAY";
	case SDL_SCANCODE_AUDIOMUTE: return L"SDL_SCANCODE_AUDIOMUTE";
	case SDL_SCANCODE_MEDIASELECT: return L"SDL_SCANCODE_MEDIASELECT";
	case SDL_SCANCODE_WWW: return L"SDL_SCANCODE_WWW";
	case SDL_SCANCODE_MAIL: return L"SDL_SCANCODE_MAIL";
	case SDL_SCANCODE_CALCULATOR: return L"SDL_SCANCODE_CALCULATOR";
	case SDL_SCANCODE_COMPUTER: return L"SDL_SCANCODE_COMPUTER";
	case SDL_SCANCODE_AC_SEARCH: return L"SDL_SCANCODE_AC_SEARCH";
	case SDL_SCANCODE_AC_HOME: return L"SDL_SCANCODE_AC_HOME";
	case SDL_SCANCODE_AC_BACK: return L"SDL_SCANCODE_AC_BACK";
	case SDL_SCANCODE_AC_FORWARD: return L"SDL_SCANCODE_AC_FORWARD";
	case SDL_SCANCODE_AC_STOP: return L"SDL_SCANCODE_AC_STOP";
	case SDL_SCANCODE_AC_REFRESH: return L"SDL_SCANCODE_AC_REFRESH";
	case SDL_SCANCODE_AC_BOOKMARKS: return L"SDL_SCANCODE_AC_BOOKMARKS";
	case SDL_SCANCODE_BRIGHTNESSDOWN: return L"SDL_SCANCODE_BRIGHTNESSDOWN";
	case SDL_SCANCODE_BRIGHTNESSUP: return L"SDL_SCANCODE_BRIGHTNESSUP";
	case SDL_SCANCODE_DISPLAYSWITCH: return L"SDL_SCANCODE_DISPLAYSWITCH";
	case SDL_SCANCODE_KBDILLUMTOGGLE: return L"SDL_SCANCODE_KBDILLUMTOGGLE";
	case SDL_SCANCODE_KBDILLUMDOWN: return L"SDL_SCANCODE_KBDILLUMDOWN";
	case SDL_SCANCODE_KBDILLUMUP: return L"SDL_SCANCODE_KBDILLUMUP";
	case SDL_SCANCODE_EJECT: return L"SDL_SCANCODE_EJECT";
	case SDL_SCANCODE_SLEEP: return L"SDL_SCANCODE_SLEEP";
	case SDL_SCANCODE_APP1: return L"SDL_SCANCODE_APP1";
	case SDL_SCANCODE_APP2: return L"SDL_SCANCODE_APP2";
	case SDL_SCANCODE_AUDIOREWIND: return L"SDL_SCANCODE_AUDIOREWIND";
	case SDL_SCANCODE_AUDIOFASTFORWARD: return L"SDL_SCANCODE_AUDIOFASTFORWARD";
		//case SDL_NUM_SCANCODES               : return L"SDL_NUM_SCANCODES";
	}
	return L"SDL_SCANCODE_UNKNOWN";
}



// Debug時のDEBUGPRINTマクロとDEBUGPRINTLNマクロ
#if _DEBUG && defined(_WIN32)
#include <windows.h>
#include <debugapi.h>

inline void __cdecl DebugPrintf(bool bOutputMB, const char* fmt, ...)
{
	char     tmp[1024];
	va_list  ap;

	va_start(ap, fmt);
	vsprintf(tmp, fmt, ap);

	// VisualStudioのデバッグウィンドウには必ず出力する
	OutputDebugStringA(tmp);

	if (bOutputMB)
	{
		// メッセージボックスはフラグがONにされたときだけ出力
		::MessageBoxA(NULL, tmp, "DEBUG MESSAGE", MB_OK);
	}

	va_end(ap);
}

inline void __cdecl DebugPrintf(bool bOutputMB, const wchar_t* fmt, ...)
{
	wchar_t  tmp[1024];
	va_list  ap;

	va_start(ap, fmt);
	vswprintf(tmp, fmt, ap);

	// VisualStudioのデバッグウィンドウには必ず出力する
	OutputDebugStringW(tmp);

	if (bOutputMB)
	{
		// メッセージボックスはフラグがONにされたときだけ出力
		::MessageBoxW(NULL, tmp, L"DEBUG MESSAGE", MB_OK);
	}

	va_end(ap);
}

#define DEBUGPRINT DebugPrintf

inline void __cdecl DebugPrintfln(bool bOutputMB, const char* fmt, ...)
{
	char     tmp[1024];
	va_list  ap;

	va_start(ap, fmt);
	vsprintf(tmp, fmt, ap);
	::strcat(tmp, "\n");

	// VisualStudioのデバッグウィンドウには必ず出力する
	OutputDebugStringA(tmp);

	if (bOutputMB)
	{
		// メッセージボックスはフラグがONにされたときだけ出力
		::MessageBoxA(NULL, tmp, "DEBUG MESSAGE", MB_OK);
	}

	va_end(ap);
}

inline void __cdecl DebugPrintfln(bool bOutputMB, const wchar_t* fmt, ...)
{
	wchar_t  tmp[1024];
	va_list  ap;

	va_start(ap, fmt);
	vswprintf(tmp, fmt, ap);
	::wcscat(tmp, L"\n");

	// VisualStudioのデバッグウィンドウには必ず出力する
	OutputDebugStringW(tmp);

	if (bOutputMB)
	{
		// メッセージボックスはフラグがONにされたときだけ出力
		::MessageBoxW(NULL, tmp, L"DEBUG MESSAGE", MB_OK);
	}

	va_end(ap);
}

#define DEBUGPRINTLN DebugPrintfln

#elif defined(_WIN32)
#include <windows.h>
#include <debugapi.h>

inline void __cdecl DebugPrintfln(bool bOutputMB, const char* fmt, ...)
{
	char  tmp[1024];

	if (bOutputMB)    // リリース時はメッセージボックスのみ出力
	{
		va_list ap;

		va_start(ap, fmt);

		vsprintf(tmp, fmt, ap);
		::strcat(tmp, "\n");

		::MessageBoxA(NULL, tmp, "DEBUG MESSAGE", MB_OK);

		va_end(ap);
	}
}

inline void __cdecl DebugPrintfln(bool bOutputMB, const wchar_t* fmt, ...)
{
	wchar_t  tmp[1024];

	if (bOutputMB)    // リリース時はメッセージボックスのみ出力
	{
		va_list ap;

		va_start(ap, fmt);

		vswprintf(tmp, fmt, ap);
		::wcscat(tmp, L"\n");

		::MessageBoxW(NULL, tmp, L"DEBUG MESSAGE", MB_OK);

		va_end(ap);
	}
}

// リリース時は何もしない
//#define SdlScanCodeString(...) __noop
#define DEBUGPRINT(...) __noop
#define DEBUGPRINTLN DebugPrintfln

#else

	//#define SdlScanCodeString(...) __noop
#define DEBUGPRINT(...) __noop
#define DEBUGPRINTLN(...) __noop

#endif

#endif//#ifndef __DEBUG_RPINT_H__
